### ISSUE TITLE
does not working with Godot 3.2.1

### ISSUE THREAD

**Issue by spoadr** [oxben/TowerDefense#2]
global.gd needs an update

all `get_tree().call_group()` needs to update form e.g.

`get_tree().call_group(0,"CashListeners","on_cash_update")`

to

`get_tree().call_group("CashListeners","on_cash_update")`

**Comment by oxben** [comment]
Thanks for reporting the issue I'll have a look at it soon.

**Comment by oxben** [comment]
Fixed
